name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Volta
        uses: volta-cli/action@v4

      - name: Install pinned toolchain
        run: |
          NODE_VERSION=$(jq -r '.volta.node' package.json)
          PNPM_VERSION=$(jq -r '.volta.pnpm' package.json)
          volta install node@"$NODE_VERSION"
          volta install pnpm@"$PNPM_VERSION"

      - name: Show tool versions
        run: |
          volta --version
          node --version
          pnpm --version

      - name: Determine pnpm store path
        id: pnpm-store
        run: echo "store=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.store }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Format Check
        run: pnpm format:check

      - name: Test
        run: pnpm -r test

      - name: Build
        run: pnpm -r build
